
spring:
  mvc:    throw-exception-if-no-handler-found: true
  h2:    console:      path: /h2-console
      settings:        trace: false
        web-allow-others: false
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    show-sql: true
    open-in-view: false
    hibernate:      ddl-auto: create-drop
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    
logging:
  file:    name: demo.log  
    
    